version: '3'

services:
  node-app:
    build: .
    image: node:14
    environment:
      - RETHINKDB_URL=rethinkdb://rethinkdb:5000/lunar_db
    ports:
      - '3000:3000'
    depends_on:
      - rethinkdb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  rethinkdb:
    image: rethinkdb:2.4.1-centos
    ports:
      - '5000:28015'
      - '9000:8080'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
